### ISSUE TITLE
disk with xfs bound to ldc

### ISSUE THREAD

**Issue by buffalo1024** [hwameistor/local-disk-manager#33]
Output of `lsblk`:
```
```
<img width="647" alt="image" src="https://user-images.githubusercontent.com/49835372/159665880-27fdae5a-2ba2-4a6a-98c8-c273602914ab.png">

Output of `blkid`:
```
```
<img width="857" alt="image" src="https://user-images.githubusercontent.com/49835372/159666066-a159f61e-902a-4b9b-aa57-2e0e16f6be2c.png">
Output of `kubectl version`:
```
```
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/49835372/159666173-74685a6a-6b45-48fe-bf75-d323ba745d8d.png">

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
# paste output here
```
<img width="649" alt="image" src="https://user-images.githubusercontent.com/49835372/159666323-d231dbf0-583c-403d-aa52-358d864ce9ed.png">

**Comment by SSmallMonster** [comment]
this is a bug when the disk is used directly without creating a partition

**temporary repair method**: update ld with deleting `claimRef` field

after repair:
```
[root@dce-10-6-163-21 ~]# kubectl get ld
NAME                  NODEMATCH         CLAIM   PHASE
...
10-6-163-25-sdb   10-6-163-25                   Claimed
```
