### ISSUE TITLE
[bug]README.md文档描述需要明确nodeName是node的hostname

### ISSUE THREAD

**Issue by tukwila** [hwameistor/local-disk-manager#37]
作为insight tester，我在按照README.md文档### STEP 3: Claim Disk By Type On Node创建LDC时，没有将spec.nodeName设置为node的hostname以至于LDC未到Bound状态；请明确此处设置

**Comment by SSmallMonster** [comment]
>

**Comment by SSmallMonster** [comment]
> 作为insight tester，我在按照README.md文档### STEP 3: Claim Disk By Type On Node创建LDC时，没有将spec.nodeName设置为node的hostname以至于LDC未到Bound状态；请明确此处设置

 Do youmean that the nodeName field of LDC is written incorrectly (Written as something other than hostname) or just empty
----
Can you show the content of the problem LDC?

**Comment by tukwila** [comment]
no, not incorrectly; if you can give me a suggestion in the somewhere of readme usage part that this spec.nodeName' value should be hostname; i appreciate for this.
