### ISSUE TITLE
When using disk and the reclaimPolicy is Retain, delete the PVC and delete the reserved PV, the status of ld is still inuse

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/local-disk-manager#56]
When using disk and the reclaimPolicy is Retain, delete the PVC and delete the reserved PV, the status of ld is still inuse
![图片](https://user-images.githubusercontent.com/76234281/170642932-4ffb4ed8-8557-4dc6-b1de-7a1046abcc9c.png)

**Comment by SSmallMonster** [comment]
Thanks.

It is preliminarily judged that an interface of CSI is not called. I will try to reproduce some scenarios
