### ISSUE TITLE
CSI mode does not work properly

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/local-disk-manager#73]
![图片](https://user-images.githubusercontent.com/76234281/173545294-7e534cc6-9ce5-4745-8e1c-28d963ec949b.png)

![图片](https://user-images.githubusercontent.com/76234281/173545221-cac39e3c-28a7-4e48-b4ec-6200c3562532.png)

**Comment by SSmallMonster** [comment]
It's a bug about scheduler plugin, it's already fix at the version v0.1.6, please update the latest version to use Disk Volume CSI.  :-)
